### ISSUE TITLE
issue: getAllApis for a category 

### ISSUE THREAD

**Issue by johnayinde** [Zummit-Africa-Inc/zapi-lambda-core#47]
@alahirajeffrey , the get all APis belonging to a particular category does not return anything #12 
the implementation is not meant to be there it supposed  to be at the Api service that is where the joinedCoumn is.

![noreturn value](https://user-images.githubusercontent.com/38318744/192471365-744194bb-3b20-40ef-8fd7-b3c8f3f68007.PNG)

**Comment by alahirajeffrey** [comment]
I think its because the entity file was changed. The changes must have broken it.

**Comment by alahirajeffrey** [comment]
The issue has been sorted
